# Railway.app deployment configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "python app_safe.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 30
restartPolicyType = "always"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8000"
HOST = "0.0.0.0"
LOG_LEVEL = "info"
RELOAD = "false"

# Safety settings - disable real API calls initially
MOCK_REDDIT = "false"
MOCK_TWITTER = "true" 
ENABLE_REAL_MUTATES = "false"

# Reddit API credentials
REDDIT_CLIENT_ID = "mDSnWlcEn17omHHxElhLzg"
REDDIT_CLIENT_SECRET = "XF74NzwNIexlLltp_dimfdFqzJlYTA"

# Generated DATABASE_URL will be provided by Railway PostgreSQL addon
# Generated SECRET_KEY will be provided by Railway

[experimental]
incrementalBuilds = true
