# Streamlit Cloud Secrets
# Copy your environment variables here when deploying

[bigquery]
# Your GCP project and dataset
GOOGLE_CLOUD_PROJECT = "ai-adwords-470622"
BIGQUERY_DATASET_ID = "google_ads_data"

# Recommended: paste your service account JSON under this section.
# This avoids writing credential files. Fields shown below are examples.
[gcp_service_account]
# type = "service_account"
# project_id = "ai-adwords-470622"
# private_key_id = "..."
# private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
# client_email = "streamlit@ai-adwords-470622.iam.gserviceaccount.com"
# client_id = "..."
# auth_uri = "https://accounts.google.com/o/oauth2/auth"
# token_uri = "https://oauth2.googleapis.com/token"
# auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
# client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/..."

# Alternatively (not recommended on Streamlit Cloud), set the following env vars
# if you prefer file-based credentials. You must also upload the JSON file
# and write it at runtime, which is cumbersome on Streamlit Cloud.
# GOOGLE_APPLICATION_CREDENTIALS = "/path/to/service_account.json"
