# Streamlit Cloud Secrets
# Copy your environment variables here when deploying

[bigquery]
GOOGLE_CLOUD_PROJECT = "ai-adwords-470622"
BIGQUERY_DATASET_ID = "google_ads_data"

# You'll need to upload your service account JSON as a secret in Streamlit Cloud
# and reference it as GOOGLE_APPLICATION_CREDENTIALS
